#
# Konfigurační soubor WorldGuard
#
# O úpravě tohoto souboru:
# - NEPOUŽÍVEJTE TABULÁTOR. MUSÍTE používat mezery, jinak bude mít Bukkit problémy.
#   Pokud používáte editor, jako je Notepad++ (doporučeno pro uživatele Windows),
#   musíte jej nakonfigurovat tak, aby „nahradil tabulátory mezerami“.
#   V Notepad++ to lze změnit v Nastavení > Předvolby > Jazyková nabídka.
#      (Settings > Preferences > Language Menu)
# - Neodstraňujte odsazení. Texty jsou odsazeny tak, že některé položky
#   jsou v kategoriích (např. „enforce-single-session“ je v kategorii „protection“.
# - Chcete-li zkontrolovat formát tohoto souboru před jeho použitím a načtením ve
#   WorldGuard, vložte jej do http://yaml-online-parser.appspot.com/
#   a zjistěte, zda tu není nějaký „ERROR:“.
# - Řádky začínající # jsou komentáře, a proto jsou ignorovány.
#
# VAROVÁNÍ:
# Nezapomeňte zkontrolovat tabulku kompatibility pro WorldGuard, abyste zjistili,
# zda nejsou některé funkce ve vaší verzi Bukkit aktuálně poškozeny.
#

# -- This should be automatically replaced by the plugin in-game --